config/routes.rb
Rails.application.routes.draw do

  get 'conceptos/new'
  get 'sessions/new'
  get 'users/new'

  root 'static_pages#home'
  get  'ayuda' => 'static_pages#ayuda'
  get  'acercade' => 'static_pages#acercade'
  get  'contacto' => 'static_pages#contacto'
  get  'registro' => 'users#new'
  get  'autor' => 'static_pages#autor'
  get  'enlaces' => 'static_pages#enlaces'
  get  'tutor' => 'tutor#index'
  get 'login'   => 'sessions#new'
  get 'contenidos'   => 'conceptos#index'
  get 'concepto'   => 'tutor#show'
  get 'agregar_pregunta'   => 'quizes#agregar_pregunta'
  get 'agregar_respuesta'   => 'quizes#agregar_respuesta'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :conceptos
  resources :explicaciones do
    post :preview, on: :collection
  end
  resources :preguntas
  resources :respuestas
  resources :quizes do
    resource :ejercicio
    patch :evaluar, on: :member
  end

  resources :conocimientos do
    get :html, on: :collection
  end

  resources :lecciones, only: [:index, :show] do
    get 'crear/:concepto_id/:red_id', to: 'lecciones#crear', on: :collection
    resources :parte, only: [:show]
  end

  resources :conceptos do
    resources :comentarios, :only => [:create]
  end
end

app/models/concepto.rb
class Concepto < ActiveRecord::Base
  has_one :explicacion
  has_many :conocimientos
  has_many :preguntas
  has_many :probabilidades
  has_one :nodo
  has_one :quiz
  has_many :redes, through: :nodos
  has_many :partes
  has_many :comentarios

  scope :completo, -> {
    includes({
      explicacion: {},
      comentarios: {user: {}},
      quiz: {
        preguntas: {tipo_pregunta: {}},
        ejercicio: {}
      }
    })
  }
end

app/controllers/conceptos_controller.rb
class ConceptosController < ApplicationController
  before_action :set_concepto, only: [:show, :edit, :update, :destroy]

  def index
    @conceptos = Concepto.paginate(page: params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @concepto = Concepto.new
  end

  def edit
  end

  def create
    @concepto = Concepto.new(concepto_params)

    respond_to do |format|
      if @concepto.save
        format.html { redirect_to @concepto, notice: 'El concepto fue creado.' }
        format.json { render :show, status: :created, location: @concepto }
      else
        format.html { render :new }
        format.json { render json: @concepto.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @concepto.update(concepto_params)
        format.html { redirect_to @concepto, notice: 'El concepto fue actualizado.' }
        format.json { render :show, status: :ok, location: @concepto }
      else
        format.html { render :edit }
        format.json { render json: @concepto.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @concepto.destroy
    respond_to do |format|
      format.html { redirect_to conceptos_url, notice: 'El concepto fue destruído.' }
      format.json { head :no_content }
    end
  end

  private

    def set_concepto
      @concepto = Concepto.find(params[:id])
    end

    def concepto_params
      params.require(:concepto).permit(:nombre, :nivel)
    end
end

app/helpers/conceptos_helper.rb
module ConceptosHelper
end

app/views/conceptos/_concepto.html.erb
<li>
  <h3><%= concepto.nombre %></h3>
  <%= link_to "Editar explicacion", edit_explicacion_path(concepto.id) %> |
  <%= link_to "Editar Evaluación", edit_quiz_path(concepto.id) %>
  <% if concepto.quiz && concepto.quiz.ejercicio %>
    | <%= link_to "Editar Práctica", edit_quiz_ejercicio_path(concepto.quiz, id: concepto.quiz.ejercicio) %>
  <% elsif concepto.quiz %>
    | <%= link_to "Crear práctica", new_quiz_ejercicio_path(concepto.quiz.id) %>
  <% end %>
</li>

app/views/conceptos/edit.html.erb
<h1><%= @concepto.nombre %> </h1>

<p>Entendió el concepto?</p>

<% conocimiento = Conocimiento.find_by concepto_id: @concepto.id %>

<%= form_for conocimiento, url: {action: "update"} do |f| %>
  <%= radio_button(:conocido, true) %>
  <%= f.submit "Create" %>
<% end %>

app/views/conceptos/index.html.erb
<h1>Editar contenidos</h1>
<h2>Haga clic sobre el nombre del concepto para editar los contenidos relacionados</h2>
<%= will_paginate %>
  <ul class="conceptos">
    <%= render @conceptos %>
  </ul>
<%= will_paginate %>

app/views/conceptos/new.html.erb
<h1>Conceptos#new</h1>
<p>Find me in app/views/conceptos/new.html.erb</p>