config/routes.rb
Rails.application.routes.draw do

  get 'conceptos/new'
  get 'sessions/new'
  get 'users/new'

  root 'static_pages#home'
  get  'ayuda' => 'static_pages#ayuda'
  get  'acercade' => 'static_pages#acercade'
  get  'contacto' => 'static_pages#contacto'
  get  'registro' => 'users#new'
  get  'autor' => 'static_pages#autor'
  get  'enlaces' => 'static_pages#enlaces'
  get  'tutor' => 'tutor#index'
  get 'login'   => 'sessions#new'
  get 'contenidos'   => 'conceptos#index'
  get 'concepto'   => 'tutor#show'
  get 'agregar_pregunta'   => 'quizes#agregar_pregunta'
  get 'agregar_respuesta'   => 'quizes#agregar_respuesta'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :conceptos
  resources :explicaciones do
    post :preview, on: :collection
  end
  resources :preguntas
  resources :respuestas
  resources :quizes do
    resource :ejercicio
    patch :evaluar, on: :member
  end

  resources :conocimientos do
    get :html, on: :collection
  end

  resources :lecciones, only: [:index, :show] do
    get 'crear/:concepto_id/:red_id', to: 'lecciones#crear', on: :collection
    resources :parte, only: [:show]
  end

  resources :conceptos do
    resources :comentarios, :only => [:create]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      redirect_to tutor_path
    end
  end

  def ayuda
  end

  def acercade
  end

  def contacto
  end

  def registro
  end

  def login
  end

  def autor
  end

  def enlaces
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/acercade.html.erb
<h1>Acerca de</h1>

app/views/static_pages/autor.html.erb
<h1>Autor</h1>

app/views/static_pages/ayuda.html.erb
<h1>Ayuda</h1>

app/views/static_pages/contacto.html.erb
<h1>Contacto</h1>

app/views/static_pages/enlaces.html.erb
<h1>Enlaces</h1>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><i class="fa fa-code"></i> ProgTutor</h1>
  <h2>
  	Un tutor inteligente para la enseñanza de Programación
  </h2>
  <%= link_to '<i class="fa fa-pencil-square-o"></i> Regístrese ahora'.html_safe, registro_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/registro.html.erb
<h1>Registro</h1>