config/routes.rb
Rails.application.routes.draw do

  get 'conceptos/new'
  get 'sessions/new'
  get 'users/new'

  root 'static_pages#home'
  get  'ayuda' => 'static_pages#ayuda'
  get  'acercade' => 'static_pages#acercade'
  get  'contacto' => 'static_pages#contacto'
  get  'registro' => 'users#new'
  get  'autor' => 'static_pages#autor'
  get  'enlaces' => 'static_pages#enlaces'
  get  'tutor' => 'tutor#index'
  get 'login'   => 'sessions#new'
  get 'contenidos'   => 'conceptos#index'
  get 'concepto'   => 'tutor#show'
  get 'agregar_pregunta'   => 'quizes#agregar_pregunta'
  get 'agregar_respuesta'   => 'quizes#agregar_respuesta'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :conceptos
  resources :explicaciones do
    post :preview, on: :collection
  end
  resources :preguntas
  resources :respuestas
  resources :quizes do
    resource :ejercicio
    patch :evaluar, on: :member
  end

  resources :conocimientos do
    get :html, on: :collection
  end

  resources :lecciones, only: [:index, :show] do
    get 'crear/:concepto_id/:red_id', to: 'lecciones#crear', on: :collection
    resources :parte, only: [:show]
  end

  resources :conceptos do
    resources :comentarios, :only => [:create]
  end
end

app/models/ejercicio.rb
class Ejercicio < ActiveRecord::Base
  belongs_to :quiz
end

app/controllers/ejercicios_controller.rb
class EjerciciosController < ApplicationController
  before_action :set_quiz
  before_action :set_ejercicio, only: [:edit, :update]

  def new
  end

  def create
    @ejercicio = Ejercicio.new(ejercicio_params)
    @ejercicio.quiz = @quiz
    @ejercicio.save
    redirect_to contenidos_url
  end

  def edit
  end

  def update
    @ejercicio.update_attributes(ejercicio_params)
    redirect_to contenidos_url
  end

  private

  def set_quiz
    @quiz = Quiz.find_by_id(params[:quiz_id])
  end

  def set_ejercicio
    @ejercicio = @quiz.ejercicio
  end

  def ejercicio_params
    params.require(:ejercicio).permit(:enunciado, :codigo_evaluador, :puntuacion)
  end
end

app/helpers/ejercicios_helper.rb
module EjerciciosHelper
end

app/views/ejercicios/_form.html.erb
<div class="row">
  <div class="col-md-11">
    <%= f.label :enunciado, "Enunciado" %>
    <%= f.text_field :enunciado, class: 'form-control' %>
  </div>
  <div class="col-md-1">
    <%= f.label :puntuacion, "Puntuacion" %>
    <%= f.text_field :puntuacion, class: 'form-control' %>
  </div>
</div>
<%= f.label :codigo_evaluador, "Código para realizar la evaluación" %>
<%= f.text_area :codigo_evaluador, cols: "30", rows: "20", id: 'yourcode', class: 'form-control' %>
<%= f.submit 'Enviar', class: 'btn btn-primary' %>

app/views/ejercicios/edit.html.erb
<h2>Editar ejercicio para <%= @quiz.concepto.nombre %> </h2>
<%= form_for @ejercicio, url: quiz_ejercicio_path(@quiz), method: :put do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/ejercicios/new.html.erb
<h2>Editar ejercicio para <%= @quiz.concepto.nombre %> </h2>
<%= form_for :ejercicio, url: quiz_ejercicio_path(@quiz), html: {id: 'target'} do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>