config/routes.rb
Rails.application.routes.draw do

  get 'conceptos/new'
  get 'sessions/new'
  get 'users/new'

  root 'static_pages#home'
  get  'ayuda' => 'static_pages#ayuda'
  get  'acercade' => 'static_pages#acercade'
  get  'contacto' => 'static_pages#contacto'
  get  'registro' => 'users#new'
  get  'autor' => 'static_pages#autor'
  get  'enlaces' => 'static_pages#enlaces'
  get  'tutor' => 'tutor#index'
  get 'login'   => 'sessions#new'
  get 'contenidos'   => 'conceptos#index'
  get 'concepto'   => 'tutor#show'
  get 'agregar_pregunta'   => 'quizes#agregar_pregunta'
  get 'agregar_respuesta'   => 'quizes#agregar_respuesta'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :conceptos
  resources :explicaciones do
    post :preview, on: :collection
  end
  resources :preguntas
  resources :respuestas
  resources :quizes do
    resource :ejercicio
    patch :evaluar, on: :member
  end

  resources :conocimientos do
    get :html, on: :collection
  end

  resources :lecciones, only: [:index, :show] do
    get 'crear/:concepto_id/:red_id', to: 'lecciones#crear', on: :collection
    resources :parte, only: [:show]
  end

  resources :conceptos do
    resources :comentarios, :only => [:create]
  end
end

app/controllers/tutor_controller.rb
class TutorController < ApplicationController

  def index
    # TODO Soporte multi-red
    @red = Red.find_by_id(1)
    @progreso = current_user.progreso_en_red(@red)
  end

  def show
    @concepto = Concepto.completo.find_by_id(params[:id])
    @comentario = Comentario.new
  end

end

app/helpers/tutor_helper.rb
module TutorHelper
  def mostrar_progreso_nivel(nivel, porcentaje)
    content_tag(:h1, "Nivel #{nivel}") +
    content_tag(:div, '', class: 'progress center-block contenedor-progreso') do
      content_tag(:div, '', class: 'progress-bar', style: "width:#{porcentaje}%")
    end +
    content_tag(:h2, "#{porcentaje}% completado")
  end
end

app/views/tutor/_comentarios.html.erb
<% if @concepto.comentarios.any? %>
  <% @concepto.comentarios.each do |comentario| %><br>
    <%= gravatar_for comentario.user %>
    <%= "#{comentario.user.name}, hace #{time_ago_in_words(comentario.created_at)}:" %><br>
    <%= comentario.mensaje %><br><br>
  <% end %>
<% else %>
  <p>No existen comentarios sobre el tema.</p>
<% end %>
<br>
<%= form_for [@concepto, @comentario] do |f| %>
  <div class="row">
    <%= f.text_area :mensaje, "rows" => "3", class: "comment-box", "placeholder" => "Escriba su comentario" %>
  </div>
  <div class="row">
    <%= f.submit "Enviar", class: "btn btn-primary col-md-3" %>
  </div>
<% end %>

app/views/tutor/_ejercicio.html.erb
<%= javascript_include_tag 'skulpt.min' %>
<%= javascript_include_tag 'skulpt-stdlib' %>
<%= javascript_include_tag 'skulpt-functions' %>
<p><%= @ejercicio.enunciado %></p>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <form id="ejercicio" data-eval-code="<%= @ejercicio.codigo_evaluador %>">
        <textarea id="yourcode" cols="40" rows="10"></textarea><br>
        <button type="button" onclick="window.runit()" class="btn btn-primary btn-sm pull-right">Ejecutar</button>
      </form>
    </div>
    <div class="col-md-6">
      <h5>Resultado:</h5>
      <pre id="output" ></pre>
    </div>
  </div>
</div>

app/views/tutor/_quiz.html.erb
<%= form_for(@quiz, url: evaluar_quiz_path(@quiz), html: { :class => 'form-horizontal' }) do |qf| %>
  <%= qf.fields_for :preguntas do |pf| %>
  <div class="well">
    <%= content_tag :h4, "#{pf.index+1}. " + pf.object.pregunta %><br>
    <!-- Shitty hidden field hack -->
    <%= pf.hidden_field :pregunta, value: pf.object.pregunta %>
    <% tipo_pregunta_id = pf.object.tipo_pregunta_id %>
    <% if tipo_pregunta_id == TipoPregunta::SIMPLE %>
      <% pf.object.respuestas.each do |respuesta| %>
      <div class="row">
      <div class="col-md-1">
        <%= pf.radio_button :seleccionada, respuesta.id %>
      </div>
      <div class="col-md-11">
        <%= respuesta.respuesta %>
      </div>
    </div>
    <br>
      <% end %>
    <% elsif tipo_pregunta_id == TipoPregunta::MULTIPLE %>
      <%= pf.fields_for :respuestas do |rf| %>
        <!-- Shitty hidden field hack -->
        <%= rf.hidden_field :respuesta, value: rf.object.respuesta %>
        <div class="row">
          <div class="col-md-1">
        <%= rf.check_box :seleccionada %>
      </div>
      <div class="col-md-11">
        <%= rf.object.respuesta %>
      </div>
      </div>
      <% end %>
    <% end %>
  </div>
  <% end %><br>
  <%= qf.submit "Enviar quiz", class: "btn btn-primary col-md-3" %>
<% end %>

app/views/tutor/index.html.erb
<%= render 'layouts/banner' %>
<% red_id = @red.id %>
<% @progreso.each do |progreso| %>
  <%= mostrar_progreso_nivel(progreso[:nivel], progreso[:progreso]) %>
  <% conocimientos_count = progreso[:conocimientos].count %>
  <% conocimientos_count <= 3 ? x = 4 : x = 3 %>
  <div class="row">
    <% progreso[:conocimientos].each do |conocimiento| %>
      <%= content_tag :div, class: "col-md-#{x}" do -%>
        <%= conocimiento_tag(conocimiento, red_id) %>
        <%= content_tag(:span, conocimiento.concepto.nombre, class: 'centered-text center-block nombre-concepto') + tag(:br) %>
      <% end %>
    <% end %>
  </div>
<% end %>
<%= render 'layouts/modal' %>

app/views/tutor/show.html.erb
<% ejercicio = @concepto.quiz && @concepto.quiz.ejercicio %>
<h1><%= @concepto.nombre %></h1>
<ul class="nav nav-pills">
  <li class="active"><a href="#teoria" data-toggle="tab" aria-expanded="true"><i class="fa fa-book"></i> Teoría</a></li>
  <li class="<%= 'disabled' unless ejercicio%>"><a href="#practica" <%= 'data-toggle="tab"'.html_safe if ejercicio %> aria-expanded="true">Práctica</a></li>
  <li><a href="#examen" data-toggle="tab" aria-expanded="true">Examen</a></li>
  <li><a href="#comentarios" data-toggle="tab" aria-expanded="true">Comentarios</a></li> 
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in" id="teoria"><br>
    <div style="padding-left: 10px; padding-right: 10px;">
      <% if @concepto.explicacion %>
        <%= @concepto.explicacion.explicacion.html_safe %>
      <% else %>
        <p>La explicación no existe.</p>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="practica"><br />
    <h3>Ejercicio en cónsola interactiva</h3>
    <% if ejercicio %>
      <%= render partial: 'ejercicio', locals: { ejercicio: @ejercicio = @concepto.quiz.ejercicio } %>
    <% end %>
  </div>
  <div class="tab-pane fade" id="examen"><br />
    <h3>Examen</h3>
    <% if @concepto.quiz %>
      <%= render partial: 'quiz', locals: { quiz: @quiz = @concepto.quiz } %>
    <% else %>
      <p>El examen no existe</p>
    <% end %>
    <br />
  </div>
  <div class="tab-pane fade" id="comentarios">
    <h3>Comentarios</h3>
    <%= render partial: 'comentarios', locals: { concepto: @concepto, comentario: @comentario } %>
  </div>
</div>